meta_product_name: "Hometastic"
meta_title: "Hometastic - Work from anywhere, at no cost!"
meta_description: "A web application to work remotely anywhere by swapping your flat and pay little to no costs! "
meta_image: "home.png" # should exist in `app/assets/images/`
